// <auto-generated />
using System;
using Admin.Repository.DataContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Admin.Repository.Migrations.Admin
{
    [DbContext(typeof(AdminDataContext))]
    [Migration("20250314095724_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.3");

            modelBuilder.Entity("Admin.Repository.Models.RequestHeaders", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool?>("_async")
                        .HasColumnType("INTEGER");

                    b.Property<string>("acceptEncoding")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("contentEncoding")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("idempotencyKey")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("zuoraEntityIds")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("zuoraTrackId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("RequestHeaders");
                });
#pragma warning restore 612, 618
        }
    }
}
