/*
 * Quickstart API Reference
 *
 * Zuora Quickstart API is recommended for new customers and integrators, allowing new integrators to swiftly integrate with Zuora. It supports essential business use cases.   To use the Quickstart API, you must have the following features enabled on your tenant:   * [Orders](https://knowledgecenter.zuora.com/Billing/Subscriptions/Orders) or [Orders Harmonization](https://knowledgecenter.zuora.com/Billing/Subscriptions/Orders/Orders_Harmonization)  * [Invoice Settlement](https://knowledgecenter.zuora.com/Billing/Billing_and_Payments/Invoice_Settlement)  To find the latest changes made to the Zuora Quickstart API, check the [Quickstart API Changelog](https://developer.zuora.com/quickstart-api/changelog/2022q4-changelog/).  We recommend that you subscribe to [Developers Community](https://community.zuora.com/communities/community-home?communitykey=e2a932b4-50c4-4019-a3e8-362e38714df3) to get notifications when a new version is released.
 *
 * OpenAPI spec version: 2024-01-10
 *
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using Service;
using Service.Interfaces;
using Service.Models;
using Swashbuckle.AspNetCore.Annotations;
using ZIP2GO.WebAPI.Attributes;
using ZIP2GO.WebAPI.Security;

namespace ZIP2GO.WebAPI.Controllers
{
    /// <summary>
    ///
    /// </summary>
    [ApiController]
    public class BillingDocumentItemsController : ControllerBase
    {
        private readonly IBillingDocumentItemsService _billingDocumentItemsService;

        public BillingDocumentItemsController(
            IBillingDocumentItemsService billingDocumentItemsService)
        {
            _billingDocumentItemsService = billingDocumentItemsService ?? throw new ArgumentNullException(nameof(billingDocumentItemsService));
        }

        /// <summary>
        /// Cancels a draft invoice
        /// </summary>
        /// <param name="invoiceId">The ID of the invoice to cancel</param>
        /// <returns>The cancelled invoice details</returns>
        /// <response code="200">Returns the cancelled invoice</response>
        /// <response code="400">Bad Request</response>
        /// <response code="401">Unauthorized</response>
        /// <response code="404">Invoice not found</response>
        /// <response code="405">Method not allowed</response>
        /// <response code="429">Too many requests</response>
        /// <response code="500">Internal server error</response>
        [HttpPost]
        [Route("/billing_document_items/{invoiceId}/cancel")]
        [Authorize(AuthenticationSchemes = BearerAuthenticationHandler.SchemeName)]
        [ValidateModelState]
        [SwaggerOperation("CancelBillingDocumentItem")]
        [SwaggerResponse(statusCode: 200, type: typeof(BillingDocumentItem), description: "Returns the cancelled invoice")]
        [SwaggerResponse(statusCode: 400, type: typeof(ErrorResponse), description: "Bad Request")]
        [SwaggerResponse(statusCode: 401, type: typeof(ErrorResponse), description: "Unauthorized")]
        [SwaggerResponse(statusCode: 404, type: typeof(ErrorResponse), description: "Invoice not found")]
        [SwaggerResponse(statusCode: 405, type: typeof(ErrorResponse), description: "Method not allowed")]
        [SwaggerResponse(statusCode: 429, type: typeof(ErrorResponse), description: "Too many requests")]
        [SwaggerResponse(statusCode: 500, type: typeof(ErrorResponse), description: "Internal server error")]
        public async Task<IActionResult> CancelBillingDocumentItem([FromRoute] string invoiceId)
        {
            //TODO: Uncomment the next line to return response 200 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(200, default(BillingDocumentItem));

            //TODO: Uncomment the next line to return response 400 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(400, default(ErrorResponse));

            //TODO: Uncomment the next line to return response 401 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(401, default(ErrorResponse));

            //TODO: Uncomment the next line to return response 404 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(404, default(ErrorResponse));

            //TODO: Uncomment the next line to return response 405 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(405, default(ErrorResponse));

            //TODO: Uncomment the next line to return response 429 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(429, default(ErrorResponse));

            //TODO: Uncomment the next line to return response 500 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(500, default(ErrorResponse));
            string exampleJson = null;
            exampleJson = "{\n  \"updated_time\" : \"2000-01-23T04:56:07.000+00:00\",\n  \"billing_document\" : \"\",\n  \"accounts_receivable_account\" : \"accounts_receivable_account\",\n  \"service_end\" : \"service_end\",\n  \"subscription_item_id\" : \"subscription_item_id\",\n  \"revenue_recognition_rule_name\" : \"revenue_recognition_rule_name\",\n  \"price_id\" : \"price_id\",\n  \"description\" : \"description\",\n  \"subscription\" : \"\",\n  \"type\" : \"credit_memo\",\n  \"applied_to_item_id\" : \"applied_to_item_id\",\n  \"on_account_account\" : \"on_account_account\",\n  \"subscription_id\" : \"subscription_id\",\n  \"subscription_item\" : \"\",\n  \"deferred_revenue_account\" : \"deferred_revenue_account\",\n  \"unit_of_measure\" : \"unit_of_measure\",\n  \"purchase_order_number\" : \"purchase_order_number\",\n  \"price_description\" : \"price_description\",\n  \"id\" : \"id\",\n  \"sku\" : \"sku\",\n  \"discount_item\" : true,\n  \"service_start\" : \"service_start\",\n  \"billing_document_id\" : \"billing_document_id\",\n  \"created_time\" : \"2000-01-23T04:56:07.000+00:00\",\n  \"recognized_revenue_account\" : \"recognized_revenue_account\",\n  \"amount\" : 0.8008281904610115,\n  \"quantity\" : 1.4658129805029452,\n  \"remaining_balance\" : 5.962133916683182,\n  \"custom_fields\" : \"\",\n  \"invoice_item_id\" : \"invoice_item_id\",\n  \"tax_inclusive\" : true,\n  \"booking_reference\" : \"booking_reference\",\n  \"tax\" : 2.3021358869347655,\n  \"unit_amount\" : 5.637376656633329,\n  \"product_name\" : \"product_name\",\n  \"accounting_code\" : \"accounting_code\",\n  \"tax_code\" : \"tax_code\",\n  \"document_item_date\" : \"2022-01-01T07:08:12-07:00\",\n  \"custom_objects\" : \"\",\n  \"subtotal\" : 6.027456183070403,\n  \"name\" : \"name\",\n  \"updated_by_id\" : \"updated_by_id\",\n  \"created_by_id\" : \"created_by_id\",\n  \"taxation_items\" : \"\"\n}";

            var example = exampleJson != null
            ? JsonConvert.DeserializeObject<BillingDocumentItem>(exampleJson)
            : default(BillingDocumentItem);            //TODO: Change the data returned
            return new ObjectResult(example);
        }

        /// <summary>
        /// Creates a new invoice
        /// </summary>
        /// <param name="body">The invoice creation request details</param>
        /// <returns>The created invoice</returns>
        /// <response code="201">Returns the created invoice</response>
        /// <response code="400">Bad Request</response>
        /// <response code="401">Unauthorized</response>
        /// <response code="404">Not found</response>
        /// <response code="405">Method not allowed</response>
        /// <response code="429">Too many requests</response>
        /// <response code="500">Internal server error</response>
        [HttpPost]
        [Route("/billing_document_items")]
        [Authorize(AuthenticationSchemes = BearerAuthenticationHandler.SchemeName)]
        [ValidateModelState]
        [SwaggerOperation("CreateBillingDocumentItem")]
        [SwaggerResponse(statusCode: 201, type: typeof(BillingDocumentItem), description: "Returns the created invoice")]
        [SwaggerResponse(statusCode: 400, type: typeof(ErrorResponse), description: "Bad Request")]
        [SwaggerResponse(statusCode: 401, type: typeof(ErrorResponse), description: "Unauthorized")]
        [SwaggerResponse(statusCode: 404, type: typeof(ErrorResponse), description: "Not found")]
        [SwaggerResponse(statusCode: 405, type: typeof(ErrorResponse), description: "Method not allowed")]
        [SwaggerResponse(statusCode: 429, type: typeof(ErrorResponse), description: "Too many requests")]
        [SwaggerResponse(statusCode: 500, type: typeof(ErrorResponse), description: "Internal server error")]
        public async Task<IActionResult> CreateBillingDocumentItem([FromBody] BillingDocumentItem body)
        {
            //TODO: Uncomment the next line to return response 201 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(201, default(BillingDocumentItem));

            //TODO: Uncomment the next line to return response 400 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(400, default(ErrorResponse));

            //TODO: Uncomment the next line to return response 401 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(401, default(ErrorResponse));

            //TODO: Uncomment the next line to return response 404 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(404, default(ErrorResponse));

            //TODO: Uncomment the next line to return response 405 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(405, default(ErrorResponse));

            //TODO: Uncomment the next line to return response 429 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(429, default(ErrorResponse));

            //TODO: Uncomment the next line to return response 500 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(500, default(ErrorResponse));
            string exampleJson = null;
            exampleJson = "{\n  \"updated_time\" : \"2000-01-23T04:56:07.000+00:00\",\n  \"billing_document\" : \"\",\n  \"accounts_receivable_account\" : \"accounts_receivable_account\",\n  \"service_end\" : \"service_end\",\n  \"subscription_item_id\" : \"subscription_item_id\",\n  \"revenue_recognition_rule_name\" : \"revenue_recognition_rule_name\",\n  \"price_id\" : \"price_id\",\n  \"description\" : \"description\",\n  \"subscription\" : \"\",\n  \"type\" : \"credit_memo\",\n  \"applied_to_item_id\" : \"applied_to_item_id\",\n  \"on_account_account\" : \"on_account_account\",\n  \"subscription_id\" : \"subscription_id\",\n  \"subscription_item\" : \"\",\n  \"deferred_revenue_account\" : \"deferred_revenue_account\",\n  \"unit_of_measure\" : \"unit_of_measure\",\n  \"purchase_order_number\" : \"purchase_order_number\",\n  \"price_description\" : \"price_description\",\n  \"id\" : \"id\",\n  \"sku\" : \"sku\",\n  \"discount_item\" : true,\n  \"service_start\" : \"service_start\",\n  \"billing_document_id\" : \"billing_document_id\",\n  \"created_time\" : \"2000-01-23T04:56:07.000+00:00\",\n  \"recognized_revenue_account\" : \"recognized_revenue_account\",\n  \"amount\" : 0.8008281904610115,\n  \"quantity\" : 1.4658129805029452,\n  \"remaining_balance\" : 5.962133916683182,\n  \"custom_fields\" : \"\",\n  \"invoice_item_id\" : \"invoice_item_id\",\n  \"tax_inclusive\" : true,\n  \"booking_reference\" : \"booking_reference\",\n  \"tax\" : 2.3021358869347655,\n  \"unit_amount\" : 5.637376656633329,\n  \"product_name\" : \"product_name\",\n  \"accounting_code\" : \"accounting_code\",\n  \"tax_code\" : \"tax_code\",\n  \"document_item_date\" : \"2022-01-01T07:08:12-07:00\",\n  \"custom_objects\" : \"\",\n  \"subtotal\" : 6.027456183070403,\n  \"name\" : \"name\",\n  \"updated_by_id\" : \"updated_by_id\",\n  \"created_by_id\" : \"created_by_id\",\n  \"taxation_items\" : \"\"\n}";

            var example = exampleJson != null
            ? JsonConvert.DeserializeObject<BillingDocumentItem>(exampleJson)
            : default(BillingDocumentItem);            //TODO: Change the data returned
            return new ObjectResult(example);
        }

        /// <summary>
        /// List billing document items
        /// </summary>
        /// <remarks>List billing document items</remarks>
        /// <param name="cursor">A cursor for use in pagination. A cursor defines the starting place in a list. For instance, if you make a list request and receive 100 objects, ending with &#x60;next_page&#x3D;W3sib3JkZXJ&#x3D;&#x60;, your subsequent call can include &#x60;cursor&#x3D;W3sib3JkZXJ&#x3D;&#x60; in order to fetch the next page of the list.</param>
        /// <param name="expand">Allows you to expand responses by including related object information in a single call. See the [Expand responses](https://developer.zuora.com/quickstart-api/tutorial/expand-responses/) section of the Quickstart API Tutorials for detailed instructions.</param>
        /// <param name="filter">A case-sensitive filter on the list. See the [Filter lists](https://developer.zuora.com/quickstart-api/tutorial/filter-lists/) section of the Quickstart API Tutorials for detailed instructions.</param>
        /// <param name="sort">A case-sensitive query parameter that specifies the sort order of the list, which can be either ascending (e.g. &#x60;account_number.asc&#x60;) or descending (e.g. &#x60;account_number.desc&#x60;). You cannot sort on properties that are arrays. If the array-type properties are specified for the &#x60;sort[]&#x60; parameter, they are ignored.</param>
        /// <param name="pageSize">The maximum number of results to return in a single page. If the specified &#x60;page_size&#x60; is less than 1 or greater than 99, Zuora will return a 400 error.</param>
        /// <param name="fields">Allows you to specify which fields are returned in the response.          &lt;details&gt;            &lt;summary&gt; Accepted values &lt;/summary&gt;              &#x60;custom_fields&#x60;, &#x60;created_by_id&#x60;, &#x60;updated_by_id&#x60;, &#x60;created_time&#x60;, &#x60;id&#x60;, &#x60;updated_time&#x60;, &#x60;price_id&#x60;, &#x60;discount_item&#x60;, &#x60;deferred_revenue_account&#x60;, &#x60;description&#x60;, &#x60;name&#x60;, &#x60;quantity&#x60;, &#x60;recognized_revenue_account&#x60;, &#x60;service_end&#x60;, &#x60;service_start&#x60;, &#x60;accounts_receivable_account&#x60;, &#x60;subscription_id&#x60;, &#x60;subscription_item_id&#x60;, &#x60;tax&#x60;, &#x60;tax_inclusive&#x60;, &#x60;unit_amount&#x60;          &lt;/details&gt;</param>
        /// <param name="taxationItemsFields">Allows you to specify which fields are returned in the response.          &lt;details&gt;            &lt;summary&gt; Accepted values &lt;/summary&gt;              &#x60;custom_fields&#x60;, &#x60;created_by_id&#x60;, &#x60;updated_by_id&#x60;, &#x60;created_time&#x60;, &#x60;id&#x60;, &#x60;updated_time&#x60;, &#x60;amount&#x60;, &#x60;amount_exempt&#x60;, &#x60;tax_date&#x60;, &#x60;jurisdiction&#x60;, &#x60;location_code&#x60;, &#x60;name&#x60;, &#x60;sales_tax_payable_account&#x60;, &#x60;tax_code&#x60;, &#x60;tax_code_name&#x60;, &#x60;tax_rate&#x60;, &#x60;tax_rate_name&#x60;, &#x60;tax_inclusive&#x60;, &#x60;tax_rate_type&#x60;          &lt;/details&gt;</param>
        /// <param name="zuoraTrackId">A custom identifier for tracking API requests. If you set a value for this header, Zuora returns the same value in the response header. This header enables you to track your API calls to assist with troubleshooting in the event of an issue. The value of this field must use the US-ASCII character set and must not include any of the following characters: colon (:), semicolon (;), double quote (\&quot;), or quote (&#x27;).</param>
        /// <param name="zuoraEntityIds">An entity ID. If you have Multi-entity enabled and the authorization token is valid for more than one entity, you must use this header to specify which entity to perform the operation on. If the authorization token is only valid for a single entity or you do not have Multi-entity enabled, you do not need to set this header.</param>
        /// <param name="idempotencyKey">Specify a unique idempotency key if you want to perform an idempotent POST or PATCH request. Do not use this header in other request types. This idempotency key should be a unique value, and the Zuora server identifies subsequent retries of the same request using this value. For more information, see [Idempotent Requests](https://developer.zuora.com/api-references/quickstart-api/tag/Idempotent-Requests/).</param>
        /// <param name="acceptEncoding">Include a &#x60;accept-encoding: gzip&#x60; header to compress responses, which can reduce the bandwidth required for a response. If specified, Zuora automatically compresses responses that contain over 1000 bytes. For more information about this header, see [Request and Response Compression](https://developer.zuora.com/api-references/quickstart-api/tag/Request-and-Response-Compression/).</param>
        /// <param name="contentEncoding">Include a &#x60;content-encoding: gzip&#x60; header to compress a request. Upload a gzipped file for the payload if you specify this header. For more information, see [Request and Response Compression](https://developer.zuora.com/api-references/quickstart-api/tag/Request-and-Response-Compression/).</param>
        /// <response code="200">Default Response</response>
        /// <response code="400">Bad Request</response>
        /// <response code="401">Unauthorized</response>
        /// <response code="404">Not Found</response>
        /// <response code="405">Method Not Allowed</response>
        /// <response code="429">Too Many Requests</response>
        /// <response code="500">Internal Server Error</response>
        /// <response code="502">Bad Gateway</response>
        /// <response code="503">Service Unavailable</response>
        /// <response code="504">Gateway Timeout</response>
        [HttpGet]
        [Route("/billing_document_items")]
        [Authorize(AuthenticationSchemes = BearerAuthenticationHandler.SchemeName)]
        [ValidateModelState]
        [SwaggerOperation("GetBillingDocumentItems")]
        [SwaggerResponse(statusCode: 200, type: typeof(BillingDocumentItemListResponse), description: "Default Response")]
        [SwaggerResponse(statusCode: 400, type: typeof(ErrorResponse), description: "Bad Request")]
        [SwaggerResponse(statusCode: 401, type: typeof(ErrorResponse), description: "Unauthorized")]
        [SwaggerResponse(statusCode: 404, type: typeof(ErrorResponse), description: "Not Found")]
        [SwaggerResponse(statusCode: 405, type: typeof(ErrorResponse), description: "Method Not Allowed")]
        [SwaggerResponse(statusCode: 429, type: typeof(ErrorResponse), description: "Too Many Requests")]
        [SwaggerResponse(statusCode: 500, type: typeof(ErrorResponse), description: "Internal Server Error")]
        [SwaggerResponse(statusCode: 502, type: typeof(ErrorResponse), description: "Bad Gateway")]
        [SwaggerResponse(statusCode: 503, type: typeof(ErrorResponse), description: "Service Unavailable")]
        [SwaggerResponse(statusCode: 504, type: typeof(ErrorResponse), description: "Gateway Timeout")]
        public async Task<IActionResult> GetBillingDocumentItems([FromQuery] string cursor, string zuoraTrackId, bool async = true)
        {
            var billingDocumentItems = _billingDocumentItemsService.GetBillingDocumentItemsCached();

            if (billingDocumentItems.Data.Count() == 0) 
            {
                billingDocumentItems = _billingDocumentItemsService.GetBillingDocumentItems(cursor, zuoraTrackId, async);
            }

            return Ok(billingDocumentItems);
        }
    }
}