/*
 * Quickstart API Reference
 *
 * Zuora Quickstart API is recommended for new customers and integrators, allowing new integrators to swiftly integrate with Zuora. It supports essential business use cases.   To use the Quickstart API, you must have the following features enabled on your tenant:   * [Orders](https://knowledgecenter.zuora.com/Billing/Subscriptions/Orders) or [Orders Harmonization](https://knowledgecenter.zuora.com/Billing/Subscriptions/Orders/Orders_Harmonization)  * [Invoice Settlement](https://knowledgecenter.zuora.com/Billing/Billing_and_Payments/Invoice_Settlement)  To find the latest changes made to the Zuora Quickstart API, check the [Quickstart API Changelog](https://developer.zuora.com/quickstart-api/changelog/2022q4-changelog/).  We recommend that you subscribe to [Developers Community](https://community.zuora.com/communities/community-home?communitykey=e2a932b4-50c4-4019-a3e8-362e38714df3) to get notifications when a new version is released.
 *
 * OpenAPI spec version: 2024-01-10
 *
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using Service;
using Service.Interfaces;
using Service.Models;
using Swashbuckle.AspNetCore.Annotations;
using System.ComponentModel.DataAnnotations;
using ZIP2GO.WebAPI.Attributes;
using ZIP2GO.WebAPI.Security;

namespace ZIP2GO.WebAPI.Controllers
{
    /// <summary>
    /// Controller responsible for managing fulfillments in the system.
    /// Provides endpoints for creating, updating, deleting, and querying fulfillments.
    /// </summary>
    [ApiController]
    public class FulfillmentsController : ControllerBase
    {
        private readonly IFulfillmentsService _fulfillmentsService;

        /// <summary>
        /// Initializes a new instance of the fulfillments controller.
        /// </summary>
        /// <param name="fulfillmentsService">Service for managing fulfillments</param>
        /// <param name="httpContextAccessor">HTTP context accessor</param>
        /// <param name="cache">Cache provider</param>
        /// <exception cref="ArgumentNullException">Thrown when any dependency is null</exception>
        public FulfillmentsController(
            IFulfillmentsService fulfillmentsService)
        {
            _fulfillmentsService = fulfillmentsService ?? throw new ArgumentNullException(nameof(fulfillmentsService));
        }

        /// <summary>
        /// Creates a new fulfillment.
        /// </summary>
        /// <param name="body">Fulfillment data to create</param>
        /// <returns>The newly created fulfillment</returns>
        /// <response code="201">Fulfillment created successfully</response>
        /// <response code="400">Invalid fulfillment data</response>
        [HttpPost]
        [Route("/fulfillments")]
        [Authorize(AuthenticationSchemes = BearerAuthenticationHandler.SchemeName)]
        [ValidateModelState]
        [SwaggerOperation("CreateFulfillment")]
        [SwaggerResponse(statusCode: 201, type: typeof(Fulfillment), description: "Default Response")]
        [SwaggerResponse(statusCode: 400, type: typeof(ErrorResponse), description: "Bad Request")]
        [SwaggerResponse(statusCode: 401, type: typeof(ErrorResponse), description: "Unauthorized")]
        [SwaggerResponse(statusCode: 404, type: typeof(ErrorResponse), description: "Not Found")]
        [SwaggerResponse(statusCode: 405, type: typeof(ErrorResponse), description: "Method Not Allowed")]
        [SwaggerResponse(statusCode: 429, type: typeof(ErrorResponse), description: "Too Many Requests")]
        [SwaggerResponse(statusCode: 500, type: typeof(ErrorResponse), description: "Internal Server Error")]
        [SwaggerResponse(statusCode: 502, type: typeof(ErrorResponse), description: "Bad Gateway")]
        [SwaggerResponse(statusCode: 503, type: typeof(ErrorResponse), description: "Service Unavailable")]
        [SwaggerResponse(statusCode: 504, type: typeof(ErrorResponse), description: "Gateway Timeout")]
        public async Task<IActionResult> CreateFulfillment([FromBody] FulfillmentCreateRequest body, [FromQuery] string zuoraTrackId, bool async = true)
        {
            var result = _fulfillmentsService.CreateFulfillment(body, zuoraTrackId, async);
            return Ok(result);
        }

        /// <summary>
        /// Creates multiple fulfillments
        /// </summary>
        /// <param name="body">The list of fulfillments to create</param>
        /// <returns>The list of created fulfillments</returns>
        [HttpPost]
        [Route("/fulfillments/bulk_create")]
        [Authorize(AuthenticationSchemes = BearerAuthenticationHandler.SchemeName)]
        [ValidateModelState]
        [SwaggerOperation("CreateFulfillments")]
        [SwaggerResponse(statusCode: 201, type: typeof(FulfillmentCreateBulkResponse), description: "Default Response")]
        [SwaggerResponse(statusCode: 400, type: typeof(ErrorResponse), description: "Bad Request")]
        [SwaggerResponse(statusCode: 401, type: typeof(ErrorResponse), description: "Unauthorized")]
        [SwaggerResponse(statusCode: 404, type: typeof(ErrorResponse), description: "Not Found")]
        [SwaggerResponse(statusCode: 405, type: typeof(ErrorResponse), description: "Method Not Allowed")]
        [SwaggerResponse(statusCode: 429, type: typeof(ErrorResponse), description: "Too Many Requests")]
        [SwaggerResponse(statusCode: 500, type: typeof(ErrorResponse), description: "Internal Server Error")]
        [SwaggerResponse(statusCode: 502, type: typeof(ErrorResponse), description: "Bad Gateway")]
        [SwaggerResponse(statusCode: 503, type: typeof(ErrorResponse), description: "Service Unavailable")]
        [SwaggerResponse(statusCode: 504, type: typeof(ErrorResponse), description: "Gateway Timeout")]
        public async Task<IActionResult> CreateFulfillments([FromBody] FulfillmentCreateBulkRequest body, [FromQuery] string zuoraTrackId, bool async = true)
        {
            var result = _fulfillmentsService.CreateFulfillments(body, zuoraTrackId, async);
            return Ok(result);
        }

        /// <summary>
        /// Deletes a fulfillment
        /// </summary>
        /// <param name="fulfillmentId">The ID of the fulfillment to delete</param>
        /// <returns>No content if successful</returns>
        [HttpDelete]
        [Route("/fulfillments/{fulfillment_id}")]
        [Authorize(AuthenticationSchemes = BearerAuthenticationHandler.SchemeName)]
        [ValidateModelState]
        [SwaggerOperation("DeleteFulfillment")]
        [SwaggerResponse(statusCode: 400, type: typeof(ErrorResponse), description: "Bad Request")]
        [SwaggerResponse(statusCode: 401, type: typeof(ErrorResponse), description: "Unauthorized")]
        [SwaggerResponse(statusCode: 404, type: typeof(ErrorResponse), description: "Not Found")]
        [SwaggerResponse(statusCode: 405, type: typeof(ErrorResponse), description: "Method Not Allowed")]
        [SwaggerResponse(statusCode: 429, type: typeof(ErrorResponse), description: "Too Many Requests")]
        [SwaggerResponse(statusCode: 500, type: typeof(ErrorResponse), description: "Internal Server Error")]
        [SwaggerResponse(statusCode: 502, type: typeof(ErrorResponse), description: "Bad Gateway")]
        [SwaggerResponse(statusCode: 503, type: typeof(ErrorResponse), description: "Service Unavailable")]
        [SwaggerResponse(statusCode: 504, type: typeof(ErrorResponse), description: "Gateway Timeout")]
        public async Task<IActionResult> DeleteFulfillment([FromRoute][Required] string fulfillmentId, [FromQuery] string zuoraTrackId, bool async = true)
        {
            _fulfillmentsService.DeleteFulfillment(fulfillmentId, zuoraTrackId, async);
            return NoContent();
        }

        /// <summary>
        /// Retrieves a fulfillment by its ID.
        /// </summary>
        /// <param name="fulfillmentId">The unique identifier of the fulfillment</param>
        /// <returns>The requested fulfillment details</returns>
        /// <response code="200">Fulfillment found and returned</response>
        /// <response code="404">Fulfillment not found</response>
        [HttpGet]
        [Route("/fulfillments/{fulfillment_id}")]
        [Authorize(AuthenticationSchemes = BearerAuthenticationHandler.SchemeName)]
        [ValidateModelState]
        [SwaggerOperation("GetFulfillment")]
        [SwaggerResponse(statusCode: 200, type: typeof(Fulfillment), description: "Default Response")]
        [SwaggerResponse(statusCode: 400, type: typeof(ErrorResponse), description: "Bad Request")]
        [SwaggerResponse(statusCode: 401, type: typeof(ErrorResponse), description: "Unauthorized")]
        [SwaggerResponse(statusCode: 404, type: typeof(ErrorResponse), description: "Not Found")]
        [SwaggerResponse(statusCode: 405, type: typeof(ErrorResponse), description: "Method Not Allowed")]
        [SwaggerResponse(statusCode: 429, type: typeof(ErrorResponse), description: "Too Many Requests")]
        [SwaggerResponse(statusCode: 500, type: typeof(ErrorResponse), description: "Internal Server Error")]
        [SwaggerResponse(statusCode: 502, type: typeof(ErrorResponse), description: "Bad Gateway")]
        [SwaggerResponse(statusCode: 503, type: typeof(ErrorResponse), description: "Service Unavailable")]
        [SwaggerResponse(statusCode: 504, type: typeof(ErrorResponse), description: "Gateway Timeout")]
        public async Task<IActionResult> GetFulfillment([FromRoute][Required] string fulfillmentId, [FromQuery] string zuoraTrackId, bool async = true)
        {
            if (string.IsNullOrEmpty(fulfillmentId)) 
            {
                return BadRequest("fulfillmentId cannot be null");
            }
            if (string.IsNullOrEmpty(zuoraTrackId)) 
            {
                return BadRequest("zuoraTrackId cannot be null");
            }

            var fulfillment = _fulfillmentsService.GetFulfillmentCached(fulfillmentId);
            if (fulfillment is null) 
            {
                fulfillment = _fulfillmentsService.GetFulfillment(fulfillmentId, zuoraTrackId, async);
            }

            return Ok(fulfillment);
        }

        /// <summary>
        /// Retrieves a list of all fulfillments.
        /// </summary>
        /// <returns>A paginated list of fulfillments</returns>
        /// <response code="200">List of fulfillments retrieved successfully</response>
        [HttpGet]
        [Route("/fulfillments")]
        [Authorize(AuthenticationSchemes = BearerAuthenticationHandler.SchemeName)]
        [ValidateModelState]
        [SwaggerOperation("GetFulfillments")]
        [SwaggerResponse(statusCode: 200, type: typeof(FulfillmentListResponse), description: "Default Response")]
        [SwaggerResponse(statusCode: 400, type: typeof(ErrorResponse), description: "Bad Request")]
        [SwaggerResponse(statusCode: 401, type: typeof(ErrorResponse), description: "Unauthorized")]
        [SwaggerResponse(statusCode: 404, type: typeof(ErrorResponse), description: "Not Found")]
        [SwaggerResponse(statusCode: 405, type: typeof(ErrorResponse), description: "Method Not Allowed")]
        [SwaggerResponse(statusCode: 429, type: typeof(ErrorResponse), description: "Too Many Requests")]
        [SwaggerResponse(statusCode: 500, type: typeof(ErrorResponse), description: "Internal Server Error")]
        [SwaggerResponse(statusCode: 502, type: typeof(ErrorResponse), description: "Bad Gateway")]
        [SwaggerResponse(statusCode: 503, type: typeof(ErrorResponse), description: "Service Unavailable")]
        [SwaggerResponse(statusCode: 504, type: typeof(ErrorResponse), description: "Gateway Timeout")]
        public async Task<IActionResult> GetFulfillments([FromQuery] string zuoraTrackId, bool async = true)
        {
            var fulfillments = _fulfillmentsService.GetFulfillmentsCached();

            if (fulfillments.Data.Count() == 0) 
            {
                fulfillments = _fulfillmentsService.GetFulfillments(zuoraTrackId, async);
            }

            return Ok(fulfillments);
        }

        /// <summary>
        /// Updates an existing fulfillment.
        /// </summary>
        /// <param name="body">Updated fulfillment data</param>
        /// <param name="fulfillmentId">ID of the fulfillment to update</param>
        /// <returns>The updated fulfillment information</returns>
        /// <response code="200">Fulfillment updated successfully</response>
        /// <response code="404">Fulfillment not found</response>
        [HttpPatch]
        [Route("/fulfillments/{fulfillment_id}")]
        [Authorize(AuthenticationSchemes = BearerAuthenticationHandler.SchemeName)]
        [ValidateModelState]
        [SwaggerOperation("UpdateFulfillment")]
        [SwaggerResponse(statusCode: 200, type: typeof(Fulfillment), description: "Default Response")]
        [SwaggerResponse(statusCode: 400, type: typeof(ErrorResponse), description: "Bad Request")]
        [SwaggerResponse(statusCode: 401, type: typeof(ErrorResponse), description: "Unauthorized")]
        [SwaggerResponse(statusCode: 404, type: typeof(ErrorResponse), description: "Not Found")]
        [SwaggerResponse(statusCode: 405, type: typeof(ErrorResponse), description: "Method Not Allowed")]
        [SwaggerResponse(statusCode: 429, type: typeof(ErrorResponse), description: "Too Many Requests")]
        [SwaggerResponse(statusCode: 500, type: typeof(ErrorResponse), description: "Internal Server Error")]
        [SwaggerResponse(statusCode: 502, type: typeof(ErrorResponse), description: "Bad Gateway")]
        [SwaggerResponse(statusCode: 503, type: typeof(ErrorResponse), description: "Service Unavailable")]
        [SwaggerResponse(statusCode: 504, type: typeof(ErrorResponse), description: "Gateway Timeout")]
        public async Task<IActionResult> UpdateFulfillment([FromBody] FulfillmentPatchRequest body, [FromRoute][Required] string fulfillmentId, [FromQuery] string zuoraTrackId, bool async = true)
        {
            var result = _fulfillmentsService.UpdateFulfillment(body, fulfillmentId, zuoraTrackId, async);
            return Ok(result);
        }
    }
}